language: bash
services: docker
sudo: required

notifications:
  slack:
    email: false
    rooms:
      - secure: g22lW6mWYBbB/aRRLCG2wnRxJ+HL9+9UTGvvU1FHaEdZb2Qb21V61Sz4U2FgA6Nabh8ZoSXPHZUfYi72I1WTEEnAOLQUEufeMmgdpESKymUfzjqmJXLwCMbeDD6YNc1uR6skWSkBfwZbZttcv4aWI6KVWnliJFwtkkTmpqYELroDxaNqBV2VsFUStVkH4yEgbUQ6AgAmVm+V7OX3seheKr3gOJ571Ae7xheGejNX2zOs0wE4Ch5XQ13I6/G+bCDIZde3a1rGy2Cj4ljwrGGOOh6lHbGsTBNx8it8+0bHEykUNteqBGlzdS+Phu3xUkRBqog1fGDLwwXxiG7Y3iSH8meGiH77Mw4I7ZAu0qoAuSuEjw7eM1f1vaDru49IZ/VpoYVtCxhtv9ydrFDmi4lNFlyzQUXwmyvPGOb7ExqAq9ZUb5Kt+xL8vMHDKe4kJLqiiDxzyuTA/Asu+l9AFfvBU17eY/5WRsGmtfZ64JluxirZPogflaxbj43/nA7oe0J52/wcfm9FGmw7O7xT/CbOD/qpRLNC4LInCmSXio4Wb7Xpj+E0ycEPCuthiAc4akuEwLw1hXSg2uxx2N5DVs+Ea7LL7MKWQ6hVxurGpWgJ0+jAJuYBfrUy46dvFnWA/tmT1h7kw8BTqGu+quUk0om76OmAmnoej9AckooAybXPodE=
    on_success: change
    
# Install the latest Docker version to allow multi-stage builds
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

# Install QEmu to allow Travis (on x86 systems) to build ARM images
install:
  - docker run --rm --privileged multiarch/qemu-user-static:register

# Load the necessary files
before_script:
  - git clone https://github.com/dperson/samba
  - cd samba
  - patch Dockerfile ../Dockerfile.patch
  
# Build and test the image
script:
  - docker build -t napnap75/rpi-samba:latest .
  - docker images

# If successful, push the images
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
      docker push napnap75/rpi-samba:latest ;
    fi
    
