1c1,7
< FROM debian:stretch
---
> FROM alpine AS builder
> RUN apk add --no-cache curl \
> 	&& curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz \
> 	&& tar xzf qemu-arm-static.tar.gz
> 
> FROM arm32v7/debian:stretch
> COPY --from=builder qemu-arm-static /usr/bin/qemu-arm-static
